### ISSUE TITLE
gulp套件己建立，己可開起，無法對兩個html檔案進行連結

### ISSUE THREAD

**Issue by cn27529** [nodejs-tw/ama#9]
_感謝使用 Node.js Taiwan AMA，以下附上簡單提問範例供參考，請把內容改成你自己遇到的問題_
# 目的

<<我希望做一個 xxxx ，達成 oooo 的效果>>
# 使用的工具

<<我在 Mac 10.10 下使用 npm 安裝 node.js 5.1.0 >>
# 操作流程

<<我下了 xxx 指令，輸入了下面的程式碼，>>
# 遇到的問題

<<它顯示 xxx is undefined>>
# 嘗試過的解法

<<我嘗試過把 xxxx 改成 oooo ，但還是遇到一樣的錯誤>>
# 程式碼

下面附上我的程式碼以及我遇到的錯誤

程式碼

``` js
console.log(hello world)
```

錯誤

```
ReferenceError: helloworld is not defined
    at repl:1:13
    at REPLServer.defaultEval (repl.js:248:27)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:412:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:210:10)
    at REPLServer.Interface._line (readline.js:549:8)
    at REPLServer.Interface._ttyWrite (readline.js:826:14)
```

**Comment by cn27529** [comment]
sorry, write error
